# Generated by Django 4.2.2 on 2023-06-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptintegration',
            name='organization_id',
            field=models.TextField(blank=True, help_text='GPT Organization ID', null=True),
        ),
    ]
